### ISSUE TITLE
Internal server error for `/api/collections/94f22c9b-0d3a-4c1c-8987-4c8e83f3a92e/material_counts`

### ISSUE THREAD

**Issue by MRuecklCC** [openeduhub/metaqs-main#104]
The following query results in a 500.
```
curl 'https://{baseUrl}/api/collections/94f22c9b-0d3a-4c1c-8987-4c8e83f3a92e/material_counts' \
  -H 'authority: c106-168.cloud.gwdg.de' \
  -H 'accept: application/json' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'origin: http://localhost:8080' \
  -H 'referer: http://localhost:8080/' \
  -H 'sec-ch-ua: "Chromium";v="103", ".Not/A)Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36' \
  --compressed
```

Stack Trace: 
```
[2022-08-18 08:49:44 +0000] [10] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette_context/middleware/raw_middleware.py", line 96, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/app/api/api.py", line 479, in material_counts_tree
    return await get_material_count_tree(node_id)
  File "/app/app/api/collections/material_counts.py", line 156, in get_material_count_tree
    children = get_children(node_id=node_id)
  File "/app/app/api/collections/material_counts.py", line 143, in get_children
    return map_elastic_response_to_model(
  File "/app/app/api/collections/utils.py", line 15, in map_elastic_response_to_model
    return [model(**glom(hit.to_dict(), specs)) for hit in response]
  File "/app/app/api/collections/utils.py", line 15, in <listcomp>
    return [model(**glom(hit.to_dict(), specs)) for hit in response]
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for MissingMaterials
description
  none is not an allowed value (type=type_error.none.not_allowed)

```

**Comment by MRuecklCC** [comment]
FYI @torsten-simon

**Comment by MRuecklCC** [comment]
I may have broken this with #98
